### ISSUE TITLE
Failed to detect host OS version (running python in sandbox to detect OS fails)

### ISSUE THREAD

**Issue by mattgodbolt** [grailbio/bazel-toolchain#32]
I've been using the toolchain for a while, but having just reinstalled bazel (removing ~/.cache/bazel et al; bazel clean --expunge etc) I now get:

```
$ bazel build //ticks2hdf5
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/command.profile.gz'
INFO: Invocation ID: aa900192-37ea-4686-91bc-5e773ae1d9ec
INFO: Call stack for the definition of repository 'llvm_toolchain' which is a llvm_toolchain (rule definition at /home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:18):
 - /home/mgodbolt/dev/core/WORKSPACE:76:1
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
	File "/home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
		_download_llvm_preconfigured(<1 more arguments>)
	File "/home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 119, in _download_llvm_preconfigured
		fail(<1 more arguments>)
Failed to detect host OS version: 

ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
	File "/home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
		_download_llvm_preconfigured(<1 more arguments>)
	File "/home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 119, in _download_llvm_preconfigured
		fail(<1 more arguments>)
Failed to detect host OS version: 

ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
	File "/home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
		_download_llvm_preconfigured(<1 more arguments>)
	File "/home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 119, in _download_llvm_preconfigured
		fail(<1 more arguments>)
Failed to detect host OS version: 
```

This is on the same OS where it was working before; although I've upgraded bazel a few times since I first got the llvm toolchain working.

I'm using bazel 1.1.0 and my OS is:

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 30 (Thirty)
Release:	30
Codename:	Thirty
```

Any ideas on how to help debug this more?

**Comment by mattgodbolt** [comment]
The empty output from the "failed to detect" seems a clue. I followed along a bit and found it's running a python program. If I run the python program directly:

```
$ python /home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/tools/llvm_release_name.py 8.0.0
clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
```

(I'm using llvm 8.0.0 - here's the snippet from the WORKSPACE:

```
http_archive(
    name = "com_grail_bazel_toolchain",
    sha256 = "8c8f4615ceb17d219c99e1caae12c2144dbc0e68c8797ccdf34de90dfa18f308",
    strip_prefix = "bazel-toolchain-78079f7da202e2424dd6d1ac523a58217d7d81ef",
    urls = ["https://github.com/grailbio/bazel-toolchain/archive/78079f7da202e2424dd6d1ac523a58217d7d81ef.zip"],
)

load("@com_grail_bazel_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "8.0.0",
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")
llvm_register_toolchains()
```

**Comment by mattgodbolt** [comment]
I just changed the code to print out the error value returned from `python`. It's returning `134`, which seems to indicate some kind of problem running `python` itself

**Comment by mattgodbolt** [comment]
Hacking the scripts to print before it calls "exec"  
```
DEBUG: /home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl:113:9: Running /usr/bin/python3 /home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/tools/llvm_release_name.py 8.0.0
```

but then running (outside the sandbox, admittedly): 
```
~/d/core (master|✔) 1.0s $ /usr/bin/python3 /home/mgodbolt/.cache/bazel/_bazel_mgodbolt/d5bad8eff3da01980a0963475d1edfc1/external/com_grail_bazel_toolchain/toolchain/tools/llvm_release_name.py 8.0.0
clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
```
This works ok..seems like something isn't working inside the sandbox (maybe)

**Comment by mattgodbolt** [comment]
For now I'm going to hardcode the `distribution` in the llvm toolchain stanza. Will update bug name to cover what appears to be the problem: running python in the sandbox is failing (with error 134, usually some nasty signal delivered).

**Comment by mattgodbolt** [comment]
Closing! This appears to be a problem with an upstream bazel wrapper (not `bazelisk`, but our home-grown equivalent!) Sorry for the noise!

**Comment by robbine** [comment]
> For now I'm going to hardcode the `distribution` in the llvm toolchain stanza. Will update bug name to cover what appears to be the problem: running python in the sandbox is failing (with error 134, usually some nasty signal delivered).

Hi, I have the same  problem. Could u please show me a way to hard code the distribution as you did. Thanks !
