### ISSUE TITLE
Python not found. bazel 3.0.0

### ISSUE THREAD

**Issue by prestonvanloon** [grailbio/bazel-toolchain#42]
```
INFO: Call stack for the definition of repository 'llvm_toolchain' which is a llvm_toolchain (rule definition at /root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:18):
 - <builtin>
 - /rbe_autoconf/project_src/WORKSPACE:29:1
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 102
                _download_llvm_preconfigured(<1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 142, in _download_llvm_preconfigured
                rctx.execute(<1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 143, in rctx.execute
                _python(rctx)
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 132, in _python
                fail("python not found")
python not found
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 102
                _download_llvm_preconfigured(<1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 142, in _download_llvm_preconfigured
                rctx.execute(<1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 143, in rctx.execute
                _python(rctx)
        File "/root/.cache/bazel/_bazel_root/bd8f6376282b6bf2b9adeeab81e3922e/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 132, in _python
                fail("python not found")
python not found
```

Trying to use llvm toolchain with rbe_autoconfig. It was working in 2.1.1, I am not sure what is causing this issue.

**Comment by siddharthab** [comment]
Maybe something has changed in `rbe_autoconfig`. The error message simply says that `python` (or `python2` or `python3`) was not  found in PATH, when looked for using [rctx.which](https://docs.bazel.build/versions/master/skylark/lib/repository_ctx.html#which).

Do you get the failure when not using `rbe_autoconfig`?

**Comment by prestonvanloon** [comment]
I didn't have this issue without rbe_autoconfig

**Comment by siddharthab** [comment]
We may need to check what changed in `rbe_autoconfig` but without a python binary on PATH, it will be difficult to make this project work without changing our python scripts to bash or something.

I think it's not unreasonable to ask for a python implementation to be on PATH. Can you follow up with the `rbe_autoconfig` team?

**Comment by siddharthab** [comment]
Closing for now. Can reopen if any action items come up for this project.

**Comment by prestonvanloon** [comment]
I believe this issue was due to the fact that my RBE builder image did not have python installed. Adding python to that builder image seems to have resolved the issue. Thanks!
