### ISSUE TITLE
Toolchain unable to recognize Pop! OS (Based on Ubuntu)

### ISSUE THREAD

**Issue by 0xKiwi** [grailbio/bazel-toolchain#44]
Hello! I've been setting up my work environment on my laptop using [Pop! OS](https://pop.system76.com/) and unfortunately stumbled on some issues with llvm recognizing my distribution.

Pop! is mainly based on Ubuntu so I'd imagine the Ubuntu toolchains would work fine for it, is there a workaround to be done or a fix that can be made? I attached my error logs below. 

Thanks!

```INFO: Call stack for the definition of repository 'llvm_toolchain' which is a llvm_toolchain (rule definition at /home/kiwi/.cache/bazel/_bazel_kiwi/58c935dd8d3e5bf853a94d2d2b1bf816/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:18):
 - <builtin>
 - /home/kiwi/Work/prysm/WORKSPACE:29:1
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
	File "/home/kiwi/.cache/bazel/_bazel_kiwi/58c935dd8d3e5bf853a94d2d2b1bf816/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 102
		_download_llvm_preconfigured(<1 more arguments>)
	File "/home/kiwi/.cache/bazel/_bazel_kiwi/58c935dd8d3e5bf853a94d2d2b1bf816/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, in _download_llvm_preconfigured
		fail(<1 more arguments>)
Failed to detect host OS version: 

Unsupported linux distribution and version: pop, 20.04
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
	File "/home/kiwi/.cache/bazel/_bazel_kiwi/58c935dd8d3e5bf853a94d2d2b1bf816/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 102
		_download_llvm_preconfigured(<1 more arguments>)
	File "/home/kiwi/.cache/bazel/_bazel_kiwi/58c935dd8d3e5bf853a94d2d2b1bf816/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, in _download_llvm_preconfigured
		fail(<1 more arguments>)
Failed to detect host OS version: 

Unsupported linux distribution and version: pop, 20.04
```

**Comment by siddharthab** [comment]
Can you add the relevant logic to these lines and check:
https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/tools/llvm_release_name.py#L70-L79

You can test yourself and submit a PR.

Thank you!

**Comment by 0xKiwi** [comment]
Hello! Thanks for the quick support! I'm sorry, I just changed back to Ubuntu. Didn't see a need to have Pop installed, sorry for the trouble.
