### ISSUE TITLE
URL to download clang timing out

### ISSUE THREAD

**Issue by goyalankit** [grailbio/bazel-toolchain#45]
Hi all, i am trying to build `tensorflow/io` project and the `llvm_toolachain` is timing out while trying to download the following artifact.
```
https://releases.llvm.org/8.0.0/clang%2Bllvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
```

Full error is:
```
 - /tensorflow-io/WORKSPACE:633:1
WARNING: Download from https://releases.llvm.org/8.0.0/clang%2Bllvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz failed: class java.io.IOException Read timed out
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
                _download_llvm_preconfigured(rctx)
        File "/root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 108, in _download_llvm_preconfigured
                rctx.download_and_extract(urls, sha256 = _llvm_distributions...], ..."))])
java.io.IOException: Error downloading [https://releases.llvm.org/8.0.0/clang%2Bllvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz] to /root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/llvm_toolchain/clang%2Bllvm-8.0.0
-x86_64-linux-gnu-ubuntu-16.04.tar.xz: Read timed out
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
                _download_llvm_preconfigured(rctx)
        File "/root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 108, in _download_llvm_preconfigured
                rctx.download_and_extract(urls, sha256 = _llvm_distributions...], ..."))])
java.io.IOException: Error downloading [https://releases.llvm.org/8.0.0/clang%2Bllvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz] to /root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/llvm_toolchain/clang%2Bllvm-8.0.0
-x86_64-linux-gnu-ubuntu-16.04.tar.xz: Read timed out
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
                _download_llvm_preconfigured(rctx)
        File "/root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 108, in _download_llvm_preconfigured
                rctx.download_and_extract(urls, sha256 = _llvm_distributions...], ..."))])
java.io.IOException: Error downloading [https://releases.llvm.org/8.0.0/clang%2Bllvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz] to /root/.cache/bazel/_bazel_root/e7191a345eeab28993b50ca7fb2aa002/external/llvm_toolchain/clang%2Bllvm-8.0.0
-x86_64-linux-gnu-ubuntu-16.04.tar.xz: Read timed out
INFO: Elapsed time: 160.831s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
It seems like [llvm_distribution](https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/internal/llvm_distributions.bzl#L158) replaces the `+` with %2B. However, the llvm release server is timing out on `%2B`. If I replace the URL with `%2b`, it works.

i.e., following URL is downloadable:
```
https://releases.llvm.org/8.0.0/clang%2bllvm-8.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
```

Not sure what's the proper fix for this is. I'd appreciate any input on how can we fix this or get around this in the meantime. 

Thanks!

**Comment by siddharthab** [comment]
Thank you for the report. This is certainly a change on the llvm server side. Something must have changed in their deployment.

The proper solution would be for the LLVM team to fix it. For users of this repo, I do have a feature for people to maintain their own mirror of LLVM distributions to avoid upstream problems like this.

But in the meanwhile, you can have a local clone of this repo, and provide the --override_repository flag.
https://docs.bazel.build/versions/master/external.html#overriding-repositories-from-the-command-line

I am a little hesitant to switch the case on our side, because people might have mirrors set up that expect upper case URL encoding. But I may do it after getting a response from the llvm team.

**Comment by siddharthab** [comment]
LLVM bug report:
https://bugs.llvm.org/show_bug.cgi?id=45834

**Comment by siddharthab** [comment]
Looks like they have resolved the issue. I have closed the bug on the LLVM bugzilla portal.
