### ISSUE TITLE
Autodetection of binary release broken for LLVM 11 on Debian 10

### ISSUE THREAD

**Issue by cceckman** [grailbio/bazel-toolchain#73]
On a Debian WSL installation:

```
∵ uname -a
Linux matildaii 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux
∵ cat /etc/debian_version
10.7
```

With this repository included at HEAD, and the declaration:
```
llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "11.0.0",
)
```

I get the following build error:

```
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/home/cceckman/.cache/bazel/_bazel_cceckman/a5e80b41158b1330576b4d583ae56185/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/home/cceckman/.cache/bazel/_bazel_cceckman/a5e80b41158b1330576b4d583ae56185/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
                fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
```

---

LLVM didn't cut LLVM 11 for 18.04, so it's not recognized in the SHAs in this repository.

It looks like the llvm_release_name script doesn't know that:
https://github.com/grailbio/bazel-toolchain/blob/f2d1ba2c9d713b2aa6e7063f6d11dd3d64aa402a/toolchain/tools/llvm_release_name.py#L96

I think the fix (at least, the point fix) is to patch that line to bump to 20.04 if the LLVM version is >= 11.

(May be a worthwhile larger refactoring to split out that conditional into multiple helpers, e.g. based on distribution?)

**Comment by ankit-scio** [comment]
I am facing this same issue with ubuntu as well https://github.com/grailbio/bazel-toolchain/blob/master/toolchain/tools/llvm_release_name.py#L89
```
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
Traceback (most recent call last):
File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
_download_llvm_preconfigured(rctx)
File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 190, column 13, in download_llvm_preconfigured
	fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-12.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
```
